### ISSUE TITLE
Missing a modpack folder breaks intialization

### ISSUE THREAD

**Issue by Geneaux** [RobotsOnDrugs/BDSM#11]
**Expected behavior**

BDSM (presumably) should create any relevant folder and download whatever's necessary, after the relevant root directory is accounted for.

*What did you expect to happen?*

Presumably, any missing folders would simply be created in accordance with the most-up-to-date modpack folder structure.

**Actual behavior**

https://i.imgur.com/codBSSS.png

*What happened instead? Describe the problem and paste any relevant errors from BDSM.log.*

Firstly, after downloading .NET Runtime 7.0.1, I then downloaded the fbx-dependent BDSM.exe and underwent the user configuration setup. After the confirmations, it would later error out and quickly close before any information could be gleaned. I would do this  a second time to no avail. I swapped the executable for the self-contained release and tried again: failed again. Finally I had the thought to start the executable again, only this time I'd use ShareX to get an actually screenshot of what's happening since the log file inexplicably gave no usable information in this case. From what I gather fomr the image, the BDSM won't run if any folder is missing which seems odd. If the purpose to download it'd make sense to simply recreate those folders.

```
[2022-12-25 20:18:28.9757] Info: Scanning the server.
[2022-12-25 20:19:09.9492] Info: Scanned 5585 files in 40963ms.
[2022-12-25 20:19:09.9492] Info: Comparing files.
[2022-12-25 20:19:27.3627] Info: Scanning the server.
[2022-12-25 20:20:08.3576] Info: Scanned 5585 files in 40970ms.
[2022-12-25 20:20:08.3576] Info: Comparing files.
[2022-12-25 20:21:54.5992] Info: Scanning the server.
[2022-12-25 20:22:35.5273] Info: Scanned 5585 files in 40902ms.
[2022-12-25 20:22:35.5273] Info: Comparing files.
[2022-12-25 20:22:47.2028] Info: Scanning the server.
[2022-12-25 20:23:27.9763] Info: Scanned 5585 files in 40749ms.
[2022-12-25 20:23:27.9763] Info: Comparing files.
```

**Required information**

```
GamePath: D:\ILLUSION\HoneySelect 2
OptionalModpacks:
  Studio: true
  BleedingEdge: false
  Userdata: false
PromptToContinue: true
```

**System information**

https://betterpaste.me/?13ea9c1fb2c749a3#6uhwayJXho3UB1DH9EPb7aGFLXB2ZyT8bRRaJ7TTDC1N

Password: EHmg6hS]&],`7!v4xE

**Additional information**

I reckon this problem may also exist for any other sideloader modpack folder.

EDIT: I should also mention the problem is easily sidesteppable by recreating the folder manually.

**Comment by RobotsOnDrugs** [comment]
Strange. I thought this was taken care of long ago. In any case, it's an easy fix.
