### ISSUE TITLE
Show list of files downloaded

### ISSUE THREAD

**Issue by 0neW0rld** [RobotsOnDrugs/BDSM#13]
It would be really helpful to have the list of files you downloaded after running an update so you know which new mods to look out for. Right now the only way to tell what you've downloaded is to read the file names as they're being downloaded, which is inconvenient for a number of reasons.

**Comment by RobotsOnDrugs** [comment]
![image](https://user-images.githubusercontent.com/306289/210022286-d4a2a57b-08b2-4f38-8a8e-2c73aa5242fc.png)
