### ISSUE TITLE
Basic error handling for network interruptions during downloading

### ISSUE THREAD

**Issue by RobotsOnDrugs** [RobotsOnDrugs/BDSM#2]
**Is your feature request related to a problem? Please describe.**
Minor or temporary network interruptions should not crash the program, and the user should be able to retry without starting over.

**Describe the solution you'd like**
`try/catch` blocks around critical methods and appropriate action based on the type of error.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ssj4maiko** [comment]
I think it's interesting to point out some of the errors may come from Timeout. I also had times where the process crashed, and if I tried running it again soon, it would tell me I had too many open connections with the server, so I had to wait some time until I run again.

So it may be interesting to add some sleep time depending on the error.
