### ISSUE TITLE
[Bug] Cant do multi file download simultaneously

### ISSUE THREAD

**Issue by noelleliem** [RobotsOnDrugs/BDSM#27]
### Problem behavior

Cant do multi file download.
Only download single file until around 95% then another file begin to download.

It was possible in 0.34.

[BDSM.log](https://github.com/RobotsOnDrugs/BDSM/files/10417077/BDSM.log)

**Comment by RobotsOnDrugs** [comment]
It's possible in all versions, but there is nothing to be gained by forcing it to always spend available connections on separate files. Whether there are multiple files going at the same time or not depends on the size of the files in the queue. It already downloads more than one piece at a time, so there would be no speed gain. 5 files x 1MB/s is the same as 1 file x 5MB/s.

**Comment by noelleliem** [comment]
oh i'm sorry i didn't explain it properly.
i don't know its my connection that doesn't want to increase the download speed or not, but i cant reach 1MB/s even though my ISP has 100Mbps bandwidth.
i'm stuck between 300-700KB/s only so i'm thinking its because the download are not done in parallel.

**Comment by RobotsOnDrugs** [comment]
I can see from your log that you're not able to establish multiple connections, so you won't be able to do much in parallel. Why that is could be for any number of reasons, but a likely one is that you have other connections already open at the same time, which would happen if you had KKManager or another instance of BDSM open at the same time. It could also be something with your connection overall or specifically with the server. Better logging of this is coming, but BDSM can't actually do a whole lot about it.
