### ISSUE TITLE
[Feature Request] download speeds

### ISSUE THREAD

**Issue by NFLD99** [RobotsOnDrugs/BDSM#35]
**Is your feature request related to a problem? Please describe.**
ability to set a bandwidth or file download parallel limits to allow faster speeds

**Describe the solution you'd like**
a config option to allow faster downloads

**Describe alternatives you've considered**
multiple instances of bdsm running at once having set "blocks" to download say 256 files each

**Additional context**
just qol updates

**Comment by RobotsOnDrugs** [comment]
It already does this kind of thing and there is nothing it can do if the server can't or won't deliver any faster speeds. The servers currently only allow 3 connections at a time and this is not something I can control. STN changed stuff on them and I'm not going to argue with him about it.

**Comment by NFLD99** [comment]
ah, okay. currently its saying 6days and thats without studio or userdata and only one at a time

**Comment by RobotsOnDrugs** [comment]
It's using all available connections, even if it's only one file at any given moment.
