### ISSUE TITLE
Support for KKManager's mod enable/disable feature

### ISSUE THREAD

**Issue by 0neW0rld** [RobotsOnDrugs/BDSM#8]
So KKManager has a feature that allows users to enable/disable mods. This is achieved by changing a mod's file extension from .zipmod to .zi_mod. I was hoping BDSM could support this feature by considering .zi_mod files when deciding which mods not to download.

P.S. this might be similar to issue #4 but I felt it was different enough that it warranted its own post.

**Comment by RobotsOnDrugs** [comment]
This would probably be good to implement just so that people who have disabled mods in that fashion don't have that disrupted. It's not a huge priority, but I suspect it will be fairly trivial and can be done for v0.3.
